#This is a docker-compose default configuration, You can change as much as you need 
version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-venanjs
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app
    networks:
      - venanjs-default

  mysqldb:
    image: mysql:8.0.21
    container_name: mysql-party
    environment:
      MYSQL_ROOT_PASSWORD: 4321
      MYSQLDB_DATABASE: sorteio
    ports:
      - 3307:3306
    volumes:
      - venanjs_default:/var/lib/mysql
    networks:
      - venanjs-default

networks:
  venanjs-default:
    driver: bridge

volumes:
  venanjs_default: {}