# --- + PROXY + ---

# Template variables:
#
# * domain = 18.219.154.90
# * name = cetim-website
# * type = proxy
# *  host = localhost
# * port = 8181

#upstream cetim-website-lb {
   #     server 3.139.253.69:8080;
#}
#
#server{
#        server_name cetim.ao;
#        listen 80;
#
#        location / {
#          proxy_set_header Host $host;
#          proxy_set_header x-Forwarded-Proto $scheme;
#          proxy_set_header x-Real-IP $remote_addr;
#          proxy_set_header x-Forwarded-For $proxy_add_x_forwarded_for;
#
#          proxy_pass http://cetim-website-lb;
#        }
#      access_log /var/log/nginx/cetim-website.log;
#      error_log /var/log/nginx/cetim-website.log;
#
#	return 301 https://www.cetim.ao$request_uri;
#}


# --- - PROXY - ---
